@startuml
entity "Агент" as Agent {
  * ID : int
  --
  Title : nvarchar
  AgentTypeID : int
  Phone : nvarchar
  Email : nvarchar
  Priority : int
}
entity "Тип агента" as AgentType {
  * ID : int
  --
  Title : nvarchar
}
entity "История приоритетов" as AgentPriorityHistory {
  * ID : int
  --
  AgentID : int
  ChangeDate : datetime
  PriorityValue : int
}
entity "Магазин" as Shop {
  * ID : int
  --
  AgentID : int
  Title : nvarchar
}
entity "Продажа продукции" as ProductSale {
  * ID : int
  --
  AgentID : int
  ProductID : int
  SaleDate : date
  ProductCount : int
}
entity "Продукция" as Product {
  * ID : int
  --
  Title : nvarchar
  MinCostForAgent : decimal
}
Agent }o--|| AgentType
Agent ||--o{ AgentPriorityHistory
Agent ||--o{ Shop
Agent ||--o{ ProductSale
Product ||--o{ ProductSale
@enduml
